### ISSUE TITLE
DORN params fixed in feature-level-generatetion ?

### ISSUE THREAD

**Issue by kaixinbear** [revisitq/Pseudo-Stereo-3D#1]
In feature level generation, have you opened the grad of DORN network ?
Have you tried to open / close the grad of DORN to validate which is better?

**Comment by revisitq** [comment]
Hi, we use a pre-trained DORN for generating the disparity map. Then use a CNN backbone to extracting disparity features. So the DORN was not involved in the training.

**Comment by revisitq** [comment]
> In feature level generation, have you opened the grad of DORN network ? Have you tried to open / close the grad of DORN to validate which is better?

Hi, we use a pre-trained DORN for generating the disparity map. Then use a CNN backbone to extracting disparity features. So the DORN was not involved in the training.

**Comment by kaixinbear** [comment]
Thanks for your reply!
