### ISSUE TITLE
Kitt 3d right image

### ISSUE THREAD

**Issue by munchmoo** [revisitq/Pseudo-Stereo-3D#3]
Hello, 

In stereo_kitti_dataset.py why do we need to import right image? From your paper virtual right image/feature is generated from left image.

Thank you.

**Comment by revisitq** [comment]
> Hello,
> 
> In stereo_kitti_dataset.py why do we need to import right image? From your paper virtual right image/feature is generated from left image.
> 
> Thank you.

Hi, the right image is not essential. You can comment the code that loads right image.

**Comment by munchmoo** [comment]
Thank you for the reply!

Then, does that mean I have to comment all the lines regarding right image in stereo_data_augmentor.py and stereo_dataset_template.py ?

**Comment by revisitq** [comment]
> Thank you for the reply!
> 
> Then, does that mean I have to comment all the lines regarding right image in stereo_data_augmentor.py and stereo_dataset_template.py ?

Yeap.
