### ISSUE TITLE
LiGA stereo model 

### ISSUE THREAD

**Issue by ksh11023** [revisitq/Pseudo-Stereo-3D#4]
Hi, thanks for the nice work!

When I was reproducing Pseudo-Stereo-3D model using LIGA stereo, I got some issue loading the pretrained parameter.

Current model shape and loaded pretrained model( second_s4_hg.iouloss.ep78.backbone-no-final-bnrelu.input-only-xyz.default-lr-policy-with-wd-decay-78ep.pth) does not match. How can I solve this problem?

![Screenshot from 2022-06-02 10-09-10](https://user-images.githubusercontent.com/50094436/171531337-5eab4633-3483-4fe9-9e46-2b887ec2c2f1.png)

**Comment by revisitq** [comment]
> Hi, thanks for the nice work!
> 
> When I was reproducing Pseudo-Stereo-3D model using LIGA stereo, I got some issue loading the pretrained parameter.
> 
> Current model shape and loaded pretrained model( second_s4_hg.iouloss.ep78.backbone-no-final-bnrelu.input-only-xyz.default-lr-policy-with-wd-decay-78ep.pth) does not match. How can I solve this problem?
> 
> ![Screenshot from 2022-06-02 10-09-10](https://user-images.githubusercontent.com/50094436/171531337-5eab4633-3483-4fe9-9e46-2b887ec2c2f1.png)

If the pretrained second model is downloaded from the LIGA-Stereo repo, it's all right even there are some mismatched weights.

**Comment by ksh11023** [comment]
Yes, the second model is downloaded from the LIGA-Stereo repo. Then does that mean, the mismatching problem that I'm getting is alright??

**Comment by revisitq** [comment]
> Yes, the second model is downloaded from the LIGA-Stereo repo. Then does that mean, the mismatching problem that I'm getting is alright??

YES.

**Comment by ksh11023** [comment]
okay thank you !
