### ISSUE TITLE
can't reproduce the paper results

### ISSUE THREAD

**Issue by ksh11023** [revisitq/Pseudo-Stereo-3D#6]
Hello,
I can't reproduce the results on the paper. Validation on Kitti Dataset is very low.  I used LIGA-Stereo for the backbone, and changed the files in this repo ( Pseudo-stereo-3d model ). I used batch size=2

<img width="497" alt="스크린샷 2022-06-22 오전 10 33 19" src="https://user-images.githubusercontent.com/50094436/174924669-3388fdaf-2a72-454c-9357-0d7673a365df.png">

However, When training I got this warning. Can this be the reason for the low results? 
Do you have any suggestions...? 

<img width="1638" alt="스크린샷 2022-06-22 오전 10 35 29" src="https://user-images.githubusercontent.com/50094436/174924560-5389dd62-ba61-4fad-9e22-44acb6f11b38.png">

Thank you !

**Comment by revisitq** [comment]
Hi, thanks for reproduce our work, here is the training log. You may check wether your configuration is wrong. We will run the code on our machine again when available.
[log_train.txt](https://github.com/revisitq/Pseudo-Stereo-3D/files/8955540/log_train.txt)

**Comment by ksh11023** [comment]
okay, Thank you for the swift reply!!
